"""unique active vote per phone number

Revision ID: 39aba88ab7db
Revises: 86b95b7e285c
Create Date: 2026-08-21 16:16:38.738821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39aba88ab7db'
down_revision: Union[str, Sequence[str], None] = '86b95b7e285c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('one_active_vote_per_phone', 'votes', ['phone_number'], unique=True, postgresql_where=sa.text("status IN ('PENDING'::vote_status, 'CONFIRMED'::vote_status)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_active_vote_per_phone', table_name='votes', postgresql_where=sa.text("status IN ('PENDING'::vote_status, 'CONFIRMED'::vote_status)"))
    # ### end Alembic commands ###
