"""withdrawal admin message tracking

Revision ID: 5a921d9062ea
Revises: 54a1d26f5f1e
Create Date: 2026-08-21 17:34:40.413599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a921d9062ea'
down_revision: Union[str, Sequence[str], None] = '54a1d26f5f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawals', sa.Column('admin_message_id', sa.BigInteger(), nullable=True))
    op.add_column('withdrawals', sa.Column('admin_channel_chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawals', 'admin_channel_chat_id')
    op.drop_column('withdrawals', 'admin_message_id')
    # ### end Alembic commands ###
