"""initial schema

Revision ID: 86b95b7e285c
Revises: 
Create Date: 2026-08-21 13:52:42.991585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b95b7e285c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('photo_file_id', sa.String(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('board_url', sa.String(), nullable=False),
    sa.Column('queue_order', sa.Integer(), nullable=False),
    sa.Column('target_votes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('confirmed_votes_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_active_project', 'projects', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_withdrawn', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('votes_confirmed_count', sa.Integer(), nullable=False),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('telegram_id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('screenshot_file_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', name='vote_status'), nullable=False),
    sa.Column('admin_message_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_channel_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_votes_created_at', 'votes', ['created_at'], unique=False)
    op.create_index('ix_votes_project_id', 'votes', ['project_id'], unique=False)
    op.create_index(op.f('ix_votes_status'), 'votes', ['status'], unique=False)
    op.create_index('ix_votes_user_status', 'votes', ['user_id', 'status'], unique=False)
    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_system', sa.Enum('HUMO', 'UZCARD', 'CLICK', 'PAYME', 'PAYNET', name='payment_system'), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='withdrawal_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawals_status'), 'withdrawals', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawals_user_id'), 'withdrawals', ['user_id'], unique=False)
    op.create_table('balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('related_vote_id', sa.Integer(), nullable=True),
    sa.Column('related_withdrawal_id', sa.Integer(), nullable=True),
    sa.Column('created_by_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_vote_id'], ['votes.id'], ),
    sa.ForeignKeyConstraint(['related_withdrawal_id'], ['withdrawals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_history_user_id'), 'balance_history', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_id', sa.BigInteger(), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('triggering_vote_id', sa.Integer(), nullable=True),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['triggering_vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_id')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_balance_history_user_id'), table_name='balance_history')
    op.drop_table('balance_history')
    op.drop_index(op.f('ix_withdrawals_user_id'), table_name='withdrawals')
    op.drop_index(op.f('ix_withdrawals_status'), table_name='withdrawals')
    op.drop_table('withdrawals')
    op.drop_index('ix_votes_user_status', table_name='votes')
    op.drop_index(op.f('ix_votes_status'), table_name='votes')
    op.drop_index('ix_votes_project_id', table_name='votes')
    op.drop_index('ix_votes_created_at', table_name='votes')
    op.drop_table('votes')
    op.drop_table('users')
    op.drop_index('one_active_project', table_name='projects', postgresql_where=sa.text('is_active = true'))
    op.drop_table('projects')
    op.drop_table('global_settings')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
    sa.Enum(name='vote_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='withdrawal_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payment_system').drop(op.get_bind(), checkfirst=True)
